HSLdevcom/parkandrideAPI

- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/sass/base.scss
Added also missing ng-show for one headline in payment methods.
> fix(checkbox): Crossbrowser styling for checkboxes.

- application/src/main/java/fi/hsl/parkandride/back/ContactDao.java
- application/src/main/java/fi/hsl/parkandride/core/back/ContactRepository.java
- application/src/main/java/fi/hsl/parkandride/core/service/ContactService.java
- application/src/main/java/fi/hsl/parkandride/core/service/FacilityService.java
- application/src/main/java/fi/hsl/parkandride/core/service/OperatorService.java
1) ensure that operator update uses path parameter for operatorId
2) authorize contact and facility update against both input and persisted data
> fix(auth): operator, facility and contact update

- application/src/main/frontend/src/app/app.js
> fix(scrolling): scroll to top on successful state change

- application/src/generated/java/fi/hsl/parkandride/back/sql/QFacility.java
- application/src/main/frontend/src/app/facilities/facilitiesTable.js
- application/src/main/frontend/src/app/facilities/facilitiesTable.tpl.html
- application/src/main/frontend/src/app/facilities/usages.js
- application/src/main/frontend/src/app/facilities/usagesList.tpl.html
- application/src/main/frontend/src/app/hubs/hubList.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/java/fi/hsl/parkandride/back/FacilityDao.java
- application/src/main/java/fi/hsl/parkandride/core/back/FacilityRepository.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Facility.java
- application/src/main/java/fi/hsl/parkandride/core/domain/FacilityInfo.java
- application/src/main/java/fi/hsl/parkandride/front/FacilityController.java
- application/src/main/java/fi/hsl/parkandride/front/geojson/FeatureCollection.java
- application/src/main/resources/db/common/V4__facilities.sql
- application/src/test/java/fi/hsl/parkandride/back/FacilityDaoTest.java
Show Facility.usages in facility listings. Simplify facilities listing data model: return only basic info in search results.
> Facilities list

- application/src/main/frontend/src/sass/_layouts.scss
Fixes issue with textarea border being cut on chrome browser.
> Overlay textarea border fix

- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/java/fi/hsl/parkandride/core/domain/PaymentMethod.java
> feat(payment-methods): update taxonomy

- application/src/generated/java/fi/hsl/parkandride/back/sql/QFacility.java
- application/src/main/frontend/src/app/facilities/facilityEdit.js
- application/src/main/frontend/src/app/facilities/facilityEdit.tpl.html
- application/src/main/frontend/src/app/facilities/facilityView.js
- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/app/hubs/hubList.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/frontend/src/common/services/FacilityResource.js
- application/src/main/frontend/src/sass/base.scss
- application/src/main/java/fi/hsl/parkandride/back/FacilityDao.java
- application/src/main/java/fi/hsl/parkandride/core/domain/FacilityPaymentInfo.java
- application/src/main/java/fi/hsl/parkandride/core/domain/PaymentMethod.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Usage.java
- application/src/main/resources/db/common/V3__enums.sql
- application/src/main/resources/db/common/V4__facilities.sql
- etc/protractor/fixtures/facilities.fixture.js
- etc/protractor/pageobjects/facilities/facilityEditPage.js
- etc/protractor/pageobjects/facilities/facilityViewPage.js
- etc/protractor/specs/facilities/facilityEdit.spec.js
- etc/protractor/specs/facilities/facilityView.spec.js
- Remove boolean parkAndRideAuthRequired
- Add Usage.HSL (travel card)
- Clear pricing clipboard and selections when new (blank) row is added
- Remove PaymentMethod.VR_CARD
> feat(fixes): demo/review fixes

- application/src/main/java/fi/hsl/parkandride/core/domain/MultilingualString.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Pricing.java
- application/src/main/java/fi/hsl/parkandride/core/service/ContactService.java
- application/src/main/java/fi/hsl/parkandride/core/service/OperatorService.java
- application/src/main/java/fi/hsl/parkandride/front/ExceptionHandlers.java
- application/src/test/java/fi/hsl/parkandride/core/domain/MultilingualStringTest.java
- parent/pom.xml
+ remove unused code 
+ Pricing.maxCapacity min value (1) validation
> Multilingual string tests

- application/src/main/frontend/bower.json
- application/src/main/frontend/src/app/components/violations/violations.js
- application/src/main/frontend/src/app/facilities/facilityMap.js
- application/src/main/frontend/src/app/facilities/facilityView.js
- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/app/hubs/hubEdit.tpl.html
- application/src/main/frontend/src/app/hubs/hubMap.js
- application/src/main/frontend/src/app/operators/operatorSelect.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/frontend/src/common/services/HubResource.js
- application/src/main/frontend/src/common/services/MapService.js
- application/src/main/frontend/src/index.html
- etc/protractor/specs/facilities/facilityEdit.spec.js
Show hubs into which selected facility belongs to.
> Facility hubs

- application/src/main/frontend/src/app/facilities/facilityEdit.js
Clear facility.pricing if pricingMethod != CUSTOM.
> fix(LIIP-210): Custom pricing validation errors if method is not CUSTOM

- application/src/main/frontend/src/app/facilities/facilityEdit.js
- application/src/main/frontend/src/app/facilities/pricingManager.js
- application/src/test/java/fi/hsl/parkandride/core/domain/ViolationTest.java
Move pricingMethod change logic to pricingManager
> Fix broken add pricing line button

- .travis.yml
- application/src/main/frontend/src/app/facilities/facilityContacts.js
> fix(facility-edit): refresh contacts always on route/state change

- application/src/main/java/fi/hsl/parkandride/front/ContactController.java
- application/src/main/java/fi/hsl/parkandride/front/FacilityController.java
- application/src/main/java/fi/hsl/parkandride/front/HubController.java
- application/src/main/java/fi/hsl/parkandride/front/OperatorController.java
- application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
- application/src/main/java/fi/hsl/parkandride/front/UserController.java
- application/src/main/resources/application-env_local.properties
Log all actions requiring authentication plus all hub and facility gets.
> feat(access-log): log relevant actions

- application/src/main/java/fi/hsl/parkandride/back/ContactDao.java
- application/src/main/java/fi/hsl/parkandride/back/FacilityDao.java
- application/src/main/java/fi/hsl/parkandride/back/HubDao.java
- application/src/main/java/fi/hsl/parkandride/back/OperatorDao.java
- application/src/main/java/fi/hsl/parkandride/back/UserDao.java
- application/src/main/java/fi/hsl/parkandride/core/domain/ContactSearch.java
- application/src/main/java/fi/hsl/parkandride/core/domain/FacilitySearch.java
- application/src/main/java/fi/hsl/parkandride/core/domain/HubSearch.java
- application/src/main/java/fi/hsl/parkandride/core/domain/OperatorSearch.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Sort.java
- application/src/main/java/fi/hsl/parkandride/core/domain/UserSearch.java
- application/src/main/java/fi/hsl/parkandride/front/UserController.java
- application/src/test/java/fi/hsl/parkandride/back/ContactDaoTest.java
- application/src/test/java/fi/hsl/parkandride/back/FacilityDaoTest.java
- application/src/test/java/fi/hsl/parkandride/back/HubDaoTest.java
This feature is unused and not in-line with other daos that don't have such functionality.
> Remove contact search by name

- .gitignore
- application/pom.xml
- etc/protractor/.gitignore
- etc/protractor/pom.xml
- parent/pom.xml
Various cleanups: Remove not-needed repositories. Bind snapshot dependencies to explicit version. Add better support for eclipse. frontend maven plugin usage cleanups.
> Build cleanup

- application/pom.xml
- application/src/main/frontend/bower.json
- application/src/main/frontend/build.config.js
- application/src/main/frontend/src/app/app.js
- application/src/main/frontend/src/app/auth/auth.js
- application/src/main/frontend/src/app/reports/reports.js
- application/src/main/frontend/src/app/reports/reports.tpl.html
- application/src/main/frontend/src/app/reports/reportsNavi.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/frontend/src/index.html
- application/src/main/java/fi/hsl/parkandride/config/CoreConfiguration.java
- application/src/main/java/fi/hsl/parkandride/core/domain/CapacityType.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Permission.java
- application/src/main/java/fi/hsl/parkandride/core/service/Excel.java
- application/src/main/java/fi/hsl/parkandride/core/service/ReportService.java
- application/src/main/java/fi/hsl/parkandride/core/service/TranslationService.java
- application/src/main/java/fi/hsl/parkandride/front/ReportController.java
- application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
- etc/scripts/gocd/deploy/deploy-dev.sh
Some enum to localized values translations still need to be done...
> First report

- application/pom.xml
- application/src/main/frontend/src/app/reports/reports.js
- application/src/main/frontend/src/app/reports/reports.tpl.html
- application/src/main/java/fi/hsl/parkandride/back/UtilizationDao.java
- application/src/main/java/fi/hsl/parkandride/config/CoreConfiguration.java
- application/src/main/java/fi/hsl/parkandride/core/back/UtilizationRepository.java
- application/src/main/java/fi/hsl/parkandride/core/domain/DayType.java
- application/src/main/java/fi/hsl/parkandride/core/domain/SameAsLatestPredictor.java
- application/src/main/java/fi/hsl/parkandride/core/domain/StrictIsoDateTimeDeserializer.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Utilization.java
- application/src/main/java/fi/hsl/parkandride/core/domain/UtilizationHistory.java
- application/src/main/java/fi/hsl/parkandride/core/domain/UtilizationSearch.java
- application/src/main/java/fi/hsl/parkandride/core/service/Excel.java
- application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java
- application/src/main/java/fi/hsl/parkandride/core/service/ReportService.java
- application/src/main/java/fi/hsl/parkandride/core/service/TranslationService.java
- application/src/main/java/fi/hsl/parkandride/front/ReportController.java
- application/src/main/java/fi/hsl/parkandride/front/ReportParameters.java
- application/src/test/java/fi/hsl/parkandride/back/Dummies.java
- application/src/test/java/fi/hsl/parkandride/back/TestConfiguration.java
- application/src/test/java/fi/hsl/parkandride/back/UtilizationDaoTest.java
Also refactor UtilizationDao to return streaming results (which moves transaction handling to outer services)
> UtilizationByTime and MaxUtilization reports with some search parameters

- application/src/main/frontend/src/app/reports/reports.js
- application/src/main/frontend/src/app/reports/reports.tpl.html
- application/src/main/java/fi/hsl/parkandride/back/FacilityDao.java
- application/src/main/java/fi/hsl/parkandride/core/domain/FacilitySearch.java
- application/src/main/java/fi/hsl/parkandride/core/service/AuthenticationService.java
- application/src/main/java/fi/hsl/parkandride/core/service/Excel.java
- application/src/main/java/fi/hsl/parkandride/core/service/ReportContext.java
- application/src/main/java/fi/hsl/parkandride/core/service/ReportService.java
- application/src/main/java/fi/hsl/parkandride/front/ReportParameters.java
- application/src/test/java/fi/hsl/parkandride/core/service/AuthenticationServiceTest.java
Add filtering of report content by operator, hub and facility.
Add autofilter to generated report excel.
> Report filtering

- application/src/generated/java/fi/hsl/parkandride/back/sql/QAppUser.java
- application/src/main/frontend/src/app/auth/auth.js
- application/src/main/frontend/src/app/auth/passwordExpiredModal.js
- application/src/main/frontend/src/app/auth/passwordExpiredModal.tpl.html
- application/src/main/frontend/src/app/auth/passwordReminderModal.js
- application/src/main/frontend/src/app/auth/passwordReminderModal.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/java/fi/hsl/parkandride/back/UserDao.java
- application/src/main/java/fi/hsl/parkandride/config/CoreConfiguration.java
- application/src/main/java/fi/hsl/parkandride/core/domain/Login.java
- application/src/main/java/fi/hsl/parkandride/core/domain/UserSecret.java
- application/src/main/java/fi/hsl/parkandride/core/service/AuthenticationService.java
- application/src/main/resources/application.properties
- application/src/main/resources/db/common/V1_1__users_and_operators.sql
- application/src/test/java/fi/hsl/parkandride/core/service/AuthenticationServiceTest.java
- application/src/test/java/fi/hsl/parkandride/core/service/UserServiceTest.java
Can someone review the code for feature LIIP-261? Chen
> feat(ui): password reminder

- etc/protractor/pageobjects/capacitiesTable.js
- etc/protractor/pageobjects/facilities/facilityViewPage.js
- etc/protractor/specs/facilities/facilityView.spec.js
The protractor test for capacities table was not actually testing anything. Maybe because of refactored variable names?
> Fix protractor test for capacities table in facilities view

- application/src/main/frontend/src/app/facilities/facilityView.js
- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/app/facilities/predictionsTable.js
- application/src/main/frontend/src/app/facilities/predictionsTable.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/frontend/src/common/services/FacilityResource.js
- application/src/main/frontend/src/sass/_capacity_table.scss
- application/src/main/java/fi/hsl/parkandride/Application.java
Adds prediction table to facility page to view utilization for 0,5,10,15,30,60 minutes for each capacity and usage type
> LIIP-260: Add predictions for facilities

- .travis.yml
Cache maven, npm, and bower artifacts in travis. Sudo needs to be disabled.
> Container-based travis config with caching

- application/src/main/frontend/src/app/facilities/facilityView.js
- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/app/facilities/predictionsTable.js
- application/src/main/frontend/src/app/facilities/predictionsTable.tpl.html
- application/src/main/frontend/src/common/services/FacilityResource.js
Refactored view logic to predictions table
> Refactor: LIIP-260 Add predictions for facilities

- application/src/main/frontend/src/app/facilities/facilityView.tpl.html
- application/src/main/frontend/src/app/facilities/predictionsTable.tpl.html
- application/src/main/java/fi/hsl/parkandride/dev/DevController.java
- application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
- etc/protractor/pageobjects/facilities/facilityViewPage.js
- etc/protractor/pageobjects/predictionsTable.js
- etc/protractor/specs/devApi.js
- etc/protractor/specs/facilities/facilityView.spec.js
Add functional tests for LIIP-260 prediction table
> LIIP-260: Protractor tests

- .idea/codeStyleSettings.xml
- application/src/main/frontend/src/app/reports/reports.js
- application/src/main/frontend/src/app/reports/reports.tpl.html
- application/src/main/frontend/src/common/services/RegionResource.js
- application/src/main/frontend/src/sass/base.scss
- application/src/main/java/fi/hsl/parkandride/back/RegionDao.java
- application/src/main/java/fi/hsl/parkandride/back/RegionRepository.java
- application/src/main/java/fi/hsl/parkandride/core/domain/RegionWithHubs.java
- application/src/main/java/fi/hsl/parkandride/front/RegionController.java
- application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
- application/src/test/java/fi/hsl/parkandride/back/RegionDaoTest.java
- etc/protractor/package.json
- etc/protractor/pageobjects/components/uiSelect.js
- etc/protractor/pageobjects/pageobjects.js
- etc/protractor/pageobjects/users/reportsPage.js
- etc/protractor/protractor.conf.js
- etc/protractor/specs/devApi.js
- etc/protractor/specs/reports/reports.spec.js
The selected facilities in the reporting page are now filtered by a combination of operator, region, and hub.  Having selected a facility and thereafter making selection excluding it, the facility in question will be marked with grey strikethrough.
> LIIP-256: Filters for reporting UI

- application/src/main/asciidoc/index.adoc
- application/src/main/java/fi/hsl/parkandride/core/domain/prediction/BasePredictionResult.java
- application/src/main/java/fi/hsl/parkandride/core/domain/prediction/HubPredictionResult.java
- application/src/main/java/fi/hsl/parkandride/core/domain/prediction/PredictionResult.java
- application/src/main/java/fi/hsl/parkandride/front/HubController.java
- application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
- application/src/test/java/fi/hsl/parkandride/docs/ApiDocumentation.java
- application/src/test/java/fi/hsl/parkandride/itest/PredictionITest.java
Adds prediction API for Hubs. The API simply sums the facilities' predictions to produce a grand total.
> LIIP-171: Hub predictions

- application/src/main/frontend/src/app/facilities/predictionsTable.tpl.html
Facilities' prediction table now displays the time of the last update in the currently available column
> LIIP-260: Display last record timestamp in prediction table

- application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java
Instead of doing one insert query per history entry, use batch insert for prediction history entries
> Use batch insert for prediction history

- application/src/main/asciidoc/index.adoc
Change contact to Petro Tamminen
> Update contact information in documentation

- application/src/main/frontend/src/app/reports/reports.js
- application/src/main/frontend/src/common/directives/dateInput.js
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/AbstractReportService.java
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/ReportParameters.java
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/ReportServiceSupport.java
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/RequestLogReportService.java
- application/src/test/java/fi/hsl/parkandride/itest/ReportingITest.java
- application/src/test/java/fi/hsl/parkandride/itest/RequestLogITest.java
- etc/protractor/pageobjects/components/components.js
- etc/protractor/pageobjects/components/datepicker.js
- etc/protractor/pageobjects/users/reportsPage.js
- etc/protractor/specs/common.js
- etc/protractor/specs/reports/reports.spec.js
* Use `LocalDate` instead of `String` in `ReportParameters`
* Add functional test for datepickers
> Convert dates in ReportParameters to LocalDates

- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/java/fi/hsl/parkandride/MDCFilter.java
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/MaxUtilizationReportService.java
- application/src/main/java/fi/hsl/parkandride/core/service/reporting/ReportContext.java
- application/src/main/java/fi/hsl/parkandride/front/ExceptionHandlers.java
- application/src/test/java/fi/hsl/parkandride/itest/ReportingITest.java
- application/src/test/java/fi/hsl/parkandride/itest/RequestLogITest.java
Fixes few bugs:
* [LIIP-257](https://hsl-liipi.atlassian.net/browse/LIIP-257): Summary report not produced when selecting certain filters
* [LIIP-256](https://hsl-liipi.atlassian.net/browse/LIIP-256): Fix typo "tarkuus"
* [LIIP-285](https://hsl-liipi.atlassian.net/browse/LIIP-285): Return 400 instead of 500 when `Liipi-Application-Id` header does not match pattern
> Report bug fixes

- application/src/main/java/fi/hsl/parkandride/core/service/reporting/MaxUtilizationReportService.java
- application/src/main/java/fi/hsl/parkandride/util/MapUtils.java
- application/src/test/java/fi/hsl/parkandride/itest/MaxUtilizationReportITest.java
Unavailable spaces were summed up incorrectly in the report.
> LIIP-282: correctly calculate unavailable spaces

- application/src/main/frontend/src/app/auth/auth.js
Fixes [LIIP-261](https://hsl-liipi.atlassian.net/browse/LIIP-261). User was able to bypass the forced password change popup by reloading the page.
> LIIP-261: user could log in in spite of expired password

- application/src/main/frontend/src/assets/translations-fi.json
- application/src/main/java/fi/hsl/parkandride/dev/DevHelper.java
Fixes to issues found in tests.
> fix(i18n): fix typo and add missing dots.

- .idea/jsLibraryMappings.xml
- application/src/main/frontend/src/app/auth/auth.js
Fixes an outlying issue where the user was not permitted to change password after expiration
> LIIP-284: Password reminder dialog can be bypassed with page refresh

- application/src/main/frontend/src/app/users/userModal.tpl.html
- application/src/main/frontend/src/assets/translations-fi.json
- etc/protractor/specs/users/users.spec.js
Closes [LIIP-269](https://hsl-liipi.atlassian.net/browse/LIIP-269)
> LIIP-269: Add new user -> compulsory data missing -> null error

- application/src/main/java/fi/hsl/parkandride/core/service/reporting/FacilityUsageReportService.java
Closes [LIIP-290](https://hsl-liipi.atlassian.net/browse/LIIP-290)
> LIIP-290: Hide future utilizations from report

- application/src/main/frontend/src/app/auth/auth.js
**NOTE**: authentication is not remembered if local storage is not
available. I.e., page refresh causes the user to be logged out.
Closes [LIIP-226](https://hsl-liipi.atlassian.net/browse/LIIP-226)
> LIIP-226: make it possible to use the app without local storage

- application/src/main/frontend/src/app/facilities/facilityEdit.tpl.html
- application/src/main/frontend/src/app/facilities/pricingEdit.tpl.html
- application/src/main/frontend/src/common/directives/util.js
Limits the maximum number of allowed characters for numeric input fields in the facility edit page
> LIIP-141: Input field validation in facility edit mode

- application/src/main/java/fi/hsl/parkandride/core/service/FacilityService.java
- application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java
- application/src/main/java/fi/hsl/parkandride/dev/DevController.java
- application/src/main/java/fi/hsl/parkandride/front/FacilityController.java
- application/src/main/java/fi/hsl/parkandride/front/HubController.java
- application/src/test/java/fi/hsl/parkandride/docs/ApiDocumentation.java
- application/src/test/java/fi/hsl/parkandride/itest/PredictionITest.java
- application/src/test/java/fi/hsl/parkandride/itest/UtilizationITest.java
- etc/protractor/specs/facilities/facilityView.spec.js
Closes [LIIP-271](https://hsl-liipi.atlassian.net/browse/LIIP-271)
> LIIP-271: Hide utilization and prediction for wrong usage and capacity types

- application/src/main/java/fi/hsl/parkandride/core/service/FacilityService.java
Closes [LIIP-279](https://hsl-liipi.atlassian.net/browse/LIIP-279)
Closes [LIIP-289](https://hsl-liipi.atlassian.net/browse/LIIP-289)
Logs a warning like
Unexpected utilization for facility id=1: usage PARK_AND_RIDE not found in [COMMERCIAL] or spaces available (1) exceeds built capacity (1000)
> LIIP-279 / LIIP-289: warning when reported usage or spaces available conflicts with the actual ones

- application/src/main/frontend/src/app/contacts/contactEdit.tpl.html
- application/src/main/frontend/src/app/facilities/facilityEdit.tpl.html
- application/src/main/frontend/src/app/operators/operators.js
Closes [LIIP-291](https://hsl-liipi.atlassian.net/browse/LIIP-291)
> LIIP-291: Fix IE11 failing in operator selection dropdown
