HSLdevcom/parkandrideAPI

application/src/main/frontend/src/app/contacts/contacts.js, application/src/main/frontend/src/app/facilities/facilityMap.js, application/src/main/frontend/src/app/operators/operators.js
Implemented for port, contact and operator modals. Login modal can be closed by clicking outside modal window.
=> fix(modals): don't close modal when clicking outside modal window

etc/scripts/gocd/deploy/deploy-asg.sh
Run `deploy-asg.sh` instead of current `deploy.sh` to deploy with auto scaling group configuration.
This just provides the script. The CI configuration change to actually run the new script needs to be done separately.
=> Autoscaling deployment script

application/src/generated/java/fi/hsl/parkandride/back/sql/QCapacityType.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QFacility.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QFacilityPredictionHistory.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QPredictor.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QUsage.java, application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java, application/src/main/java/fi/hsl/parkandride/config/JdbcConfiguration.java, application/src/main/java/fi/hsl/parkandride/core/back/PredictionRepository.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java, application/src/main/resources/db/common/V13_1__prediction_history_predictor_id.sql, application/src/test/java/fi/hsl/parkandride/back/prediction/PredictionDaoTest.java
Replaces `UtilizationKey` with `predictorId` in `facility_prediction_history`
=> LIIP-249: Save prediction history for each predictor separately

application/src/main/frontend/src/app/reports/reports.js, application/src/main/frontend/src/app/reports/reports.tpl.html, application/src/main/frontend/src/assets/translations-fi.json, application/src/main/frontend/src/common/directives/dateInput.js, application/src/main/java/fi/hsl/parkandride/core/service/MaxUtilizationReportService.java, application/src/main/java/fi/hsl/parkandride/core/util/ArgumentValidator.java, application/src/test/java/fi/hsl/parkandride/back/Dummies.java, application/src/test/java/fi/hsl/parkandride/itest/ReportingITest.java
1. Show all operators separated with commas in max utilization report
2. Correct placeholder text for capacity type filter
=> Minor fixes for reporting functionality

application/src/main/frontend/src/app/facilities/facilityView.js, application/src/main/frontend/src/app/facilities/facilityView.tpl.html, application/src/main/frontend/src/app/facilities/predictionsTable.js, application/src/main/frontend/src/app/facilities/predictionsTable.tpl.html, application/src/main/frontend/src/assets/translations-fi.json, application/src/main/frontend/src/common/services/FacilityResource.js, application/src/main/java/fi/hsl/parkandride/dev/DevController.java
Changes the layout of the prediction table. Instead of showing relative times in the heading (5min, 10min, etc.), the table now displays the absolute times for the predictions, e.g., 9:05, 9:10, etc.
Furthermore, the spaces available column data is fetched from the `/utilization` endpoint to get the latest actual utilization rate.
Changes the forecast distances to 0, 10, 20, 30, and 60 minutes.
=> LIIP-260: Prediction table layout

application/src/generated/java/fi/hsl/parkandride/back/sql/QCapacityType.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QFacility.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QFacilityCapacityHistory.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QFacilityStatusHistory.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QUnavailableCapacityHistory.java, application/src/generated/java/fi/hsl/parkandride/back/sql/QUsage.java, application/src/main/java/fi/hsl/parkandride/Application.java, application/src/main/java/fi/hsl/parkandride/back/FacilityDao.java, application/src/main/java/fi/hsl/parkandride/back/FacilityHistoryDao.java, application/src/main/java/fi/hsl/parkandride/config/CoreConfiguration.java, application/src/main/java/fi/hsl/parkandride/config/JdbcConfiguration.java, application/src/main/java/fi/hsl/parkandride/core/back/FacilityHistoryRepository.java, application/src/main/java/fi/hsl/parkandride/core/back/FacilityRepository.java, application/src/main/java/fi/hsl/parkandride/core/domain/FacilityCapacityHistory.java, application/src/main/java/fi/hsl/parkandride/core/domain/FacilityStatusHistory.java, application/src/main/java/fi/hsl/parkandride/core/domain/UnavailableCapacity.java, application/src/main/java/fi/hsl/parkandride/dev/DevHelper.java, application/src/main/resources/db/common/V16__facility_status_history.sql, application/src/main/resources/db/common/V17__facility_capacity_history.sql, application/src/main/resources/db/common/V18__facility_unavailable_capacity_history.sql, application/src/test/java/fi/hsl/parkandride/back/Dummies.java, application/src/test/java/fi/hsl/parkandride/back/FacilityDaoTest.java, application/src/test/java/fi/hsl/parkandride/back/FacilityHistoryDaoTest.java, application/src/test/java/fi/hsl/parkandride/core/domain/FacilityStatusHistoryTest.java, application/src/test/java/fi/hsl/parkandride/test/DateTimeTestUtils.java
Saves capacity and status history for facilities when changed.
**Status history**
* A status history entry is inserted when a facility is created or updated and the status or status description changes
* The entry contains the full status description at the moment of update
* The entries have start and end timestamps, the end of the current entry being `null`
* Internally, this is stored in a single table `facility_status_history`
* Existing facilities get their first status history entry when their status changes
**Capacity history**
* A capacity hsitory entry is inserted when the built or unavailable capacity of a facility changes
* The entry contains both built and unavailable capacity present at the moment of update
* The entries have start and end timestamps, the end of the current …
=> LIIP-263: Save status and capacity history for facilities

application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java, application/src/main/java/fi/hsl/parkandride/core/back/PredictionRepository.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/UtilizationHistoryList.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java, application/src/main/java/fi/hsl/parkandride/dev/DevController.java, application/src/main/java/fi/hsl/parkandride/front/UrlSchema.java
In addition to the dev REST API, modified PredictionDao to store only predictions for the following distances: 5, 10, 15, 20, 30, 45 minutes, and 1, 2, 4, 8, 12, 16, 20, 24 hours. That is, only 14 predictions are stored instead of 288 (every 5 minutes for 24 hours). In other words, this cuts down the storage requirement for prediction history by 95%.
=> LIIP-272: Add dev REST API to generate prediction history for facility

application/src/main/java/fi/hsl/parkandride/core/service/reporting/MaxUtilizationReportService.java, application/src/test/java/fi/hsl/parkandride/itest/ReportingITest.java, application/src/test/java/fi/hsl/parkandride/itest/RequestLogITest.java
[LIIP-257](https://hsl-liipi.atlassian.net/browse/LIIP-257): Fixes Max Utilization report failing silently when there were utilizations registered without corresponding built capacity for the facility. Report now shows only rows with built capacity
=> LIIP-257: ignore utilizations without built capacity

application/src/main/java/fi/hsl/parkandride/back/ListUtil.java, application/src/main/java/fi/hsl/parkandride/config/CoreConfiguration.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/AverageOfPreviousWeeksPredictor.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/RelativizedAverageOfPreviousWeeksPredictor.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/UtilizationHistory.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/UtilizationHistoryImpl.java, application/src/main/java/fi/hsl/parkandride/core/domain/prediction/UtilizationHistoryList.java, application/src/test/java/fi/hsl/parkandride/core/domain/prediction/AbstractPredictorTest.java, application/src/test/java/fi/hsl/parkandride/core/domain/prediction/AverageOfPreviousWeeksPredictorTest.java, application/src/test/java/fi/hsl/parkandride/core/domain/prediction/RelativizedAverageOfPreviousWeeksPredictorTest.java, application/src/test/java/fi/hsl/parkandride/core/domain/prediction/SameAsLatestPredictorTest.java, application/src/test/java/fi/hsl/parkandride/core/domain/prediction/UtilizationHistoryListTest.java
Implemented a simple predictor that uses the average parking facility utilization from 3 previous weeks as the basis for predicting parking facility utilization/availability, but also adapts to the current level of utilization and the magnitude of changes during the last 2 hours.
=> LIIP-270: relativize predictions

application/src/main/java/fi/hsl/parkandride/core/service/reporting/AbstractReportService.java, application/src/test/java/fi/hsl/parkandride/itest/AbstractReportingITest.java, application/src/test/java/fi/hsl/parkandride/itest/MaxUtilizationReportITest.java
The selected end date was previously not included in the reporting requests. Corrects the filter to include utilization entries during the last selected day, also.
=> LIIP-282: make report end date inclusive

application/src/main/java/fi/hsl/parkandride/core/service/reporting/Excel.java, application/src/main/java/fi/hsl/parkandride/core/service/reporting/ExcelUtil.java, application/src/main/java/fi/hsl/parkandride/core/service/reporting/FacilityUsageReportService.java, application/src/test/java/fi/hsl/parkandride/itest/AbstractReportingITest.java, application/src/test/java/fi/hsl/parkandride/itest/FacilityUsageReportITest.java, application/src/test/java/fi/hsl/parkandride/itest/MaxUtilizationReportITest.java
Adds historical status information to max utilization report as per [LIIP-283](https://hsl-liipi.atlassian.net/browse/LIIP-283). If the status changed during a day, the one that was longest in effect during 6-10 is selected.
=> LIIP-283: add status history to facility usage report

etc/scripts/gocd/build/build-release.sh
Disable the UI tests from the main build task to speed up the build process. The tests were previously run twice by the GoCD server.
=> Disable UI tests for GoCD release build

application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java
Changed prediction updating to use serializable transaction isolation in order to notice when writing fails due to race condition with another server in cluster. This should make it possible to reliably identify the race condition (and not make false matches on other errors). Deploying this minimal PR to dev/test should make it possible to verify the nature of the problem: the exception thrown should change from constraint violation to concurrency violation due to the strict isolation level.
=> Step 1 in fixing concurrency errors in related to prediction calculations

application/src/main/java/fi/hsl/parkandride/core/domain/prediction/RelativizedAverageOfPreviousWeeksPredictor.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java
Fix problem caused by replacing a predictor with a new one: if old, replaced predictor has moreUtilizations=true in database, then the scheduled prediction job tries to update predictions with the predictor, but when failing to find the old predictor from its list of installed predictors, logs a warning. This happened every 5 minutes as the moreUtilizations did not get set to false. Now, moreUtilizations is set to false even for those predictors that are not installed. This should stop the system generating warnings about this situation (warning is generated only the first time after a predictor is uninstalled).
=> Disable predictor if not installed

application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java, application/src/test/java/fi/hsl/parkandride/back/prediction/PredictionDaoTest.java
Reduce the volume of stored prediction history data by about 95%. In practice, the prediction history is now stored for only these prediction distances: 5, 10, 15, 20, 30 and 45 minutes, as well as 1, 2, 4, 8, 12, 16, 20 and 24 hours (total of 14 prediction distances). The previous version stored prediction history for 24 hours with 5 minute steps resulting in 24*12 = 288 prediction distances stored every 5 minutes for each facility (and for each different capacity & usage combination within it).
=> Liip 286 reduce prediction history data

application/src/main/java/fi/hsl/parkandride/back/prediction/PredictionDao.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java
This fix should remove the ERROR messages appearing in logs when cluster nodes update predictions, but another node has already updated them. The problem was cause by the fact that the coded did not check if a predictor was already updated. This resulted in a situation where (in a 2 node cluster) another node updated predictions and then the other tried to do the same, but failed to insert the predictions to the database because database constraint (correctly) prevented it.
Even after this fix it is possible that two nodes try to update the same predictor at the same time and another one will fail because the process starts by acquiring an exclusive row-level lock (select for update) on predictor table (to protect against concurrent update attempts). However, that should be much more rare …
=> Fix prediction generation concurrency in cluster

application/src/main/resources/logback-appenderConsole.xml, application/src/main/resources/logback-appenderWillow.xml, application/src/main/resources/logback-logging.profile_IS_UNDEFINED.xml, application/src/main/resources/logback-willow.xml
Previously, application logs were only set to willow and not logged to file on the servers. NOTE: willow setting `skipOutputRedirect` needs to be set to `true` to prevent duplicate logging in willow
=> Log to file also for willow deployments

application/src/main/java/fi/hsl/parkandride/core/domain/FacilityUtil.java, application/src/main/java/fi/hsl/parkandride/core/service/FacilityService.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java, application/src/main/java/fi/hsl/parkandride/dev/DevController.java, application/src/test/java/fi/hsl/parkandride/itest/PredictionITest.java, application/src/test/java/fi/hsl/parkandride/itest/UtilizationITest.java, etc/protractor/specs/facilities/facilityView.spec.js
Previously, utilizations were incorrectly shown if any of the capacity
types had pricing for a given usage. E.g., if a facility had capacities
for CAR and ELECTRIC_CAR with corresponding registered utilizations for
PARK_AND_RIDE and COMMERCIAL usages, the utilization and prediction
endpoints would show all four combinations even if, e.g., ELECTRIC_CAR
would only have PARK_AND_RIDE in the pricing table.
=> Hide utilization and prediction without corresponding usage in pricing table

application/src/main/java/fi/hsl/parkandride/core/service/ConcurrentAccessException.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java
This change aims to ensure that all cluster nodes notice if another node has started updating a predictor by promoting transaction isolation to repeatable read isolation level (originally tried serializable). This is an attempt to remove the log error messages (visible only in cluster environment) caused by nodes competing to update predictors.
=> Fix: predictor update synchronization in cluster

application/src/main/java/fi/hsl/parkandride/back/LiipiSQLExceptionTranslator.java, application/src/test/java/fi/hsl/parkandride/back/LiipiSQLExceptionTranslatorTest.java
LIIPI logs have had SQL exceptions where the root cause of the problem has not been visible due to the old nature of Java's SQLException class: the root cause is hidden inside SQLException as a chained exception that can be retrieved using getNextException() method. Logging systems do not support this kind of custom behaviour. This change adds a feature to the LIIPI SQLException translator that copies the chained exception references as suppressed exceptions to make them visible in logs.
=> Chained SQLExceptions visible as suppressed exceptions

application/src/test/java/fi/hsl/parkandride/core/service/PredictionServiceTest.java
Decreased probability of failure in concurrency control tests (by increasing probability that the tested code is run concurrently).
=> Decrease probability of failure in concurrency control tests

application/src/main/java/fi/hsl/parkandride/back/LockDao.java, application/src/main/java/fi/hsl/parkandride/core/back/LockRepository.java, application/src/main/java/fi/hsl/parkandride/core/service/PredictionService.java, application/src/test/java/fi/hsl/parkandride/back/LockDaoTest.java, application/src/test/java/fi/hsl/parkandride/core/service/PredictionServiceTest.java
Changed predictor updating so that cluster nodes first compete for a mutually exclusive lock on which node gets the right to update the predictors. Added more unit tests for the mutex locks and fix lock releasing so that trying to release an expired lock does not delete possible new and valid lock even if the new lock is owned by the same node.
=> Mutex lock improvements
